/*
 * WeatherKit iOS27 Provider Adapter - request.js
 * v5: dataSets 补齐 + Provider 预取缓存，降低 response 阶段等待导致 Weather App CANCEL 的概率。
 */
(() => {
  const NAME = 'WK27.Provider.request';
  const DATASETS = ['airQuality','currentWeather','dataNotice','forecastDaily','forecastHourly','forecastNextHour','forecastPeriodic','highlights','news','historicalComparisons','weatherAlerts','weatherChanges'];
  const LEVEL = { OFF:0, ERROR:1, WARN:2, INFO:3, DEBUG:4, ALL:5 };
  const DEFAULT = {
    ForceAllDataSets:'1', LogLevel:'INFO', ProviderPrefetch:'1', ProviderCacheTTL:'1800',
    NextHourProvider:'WeatherKit', AirQualityProvider:'QWeather',
    ColorfulCloudsToken:'', QWeatherHost:'devapi.qweather.com', QWeatherToken:'', WAQIToken:''
  };
  function args(s){const o=Object.assign({},DEFAULT);(s||'').split('&').forEach(p=>{const i=p.indexOf('=');if(i>0){const k=decodeURIComponent(p.slice(0,i));let v=decodeURIComponent(p.slice(i+1));o[k]=String(v).replace(/^"|"$/g,'');}});return o;}
  const ARG=args(typeof $argument === 'string' ? $argument : '');
  const LOG = LEVEL[String(ARG.LogLevel||'INFO').toUpperCase()] ?? 3;
  function log(l,m){ if(LOG >= LEVEL[l]) console.log(`[${NAME}] ${m}`); }
  function mergeDataSets(s){const seen=Object.create(null),out=[]; DATASETS.concat(String(s||'').split(',')).forEach(x=>{x=String(x||'').trim(); if(x&&!seen[x]){seen[x]=1;out.push(x);}}); return out.join(',');}
  function utcLocalMidnightShift(days){ const d=new Date(); d.setUTCDate(d.getUTCDate()+days); d.setUTCHours(16,0,0,0); return d.toISOString().replace(/\.000Z$/,'Z'); }
  function locFromUrl(url){ const u=new URL(url); const m=u.pathname.match(/\/api\/v2\/weather\/[^/]+\/(-?\d+(?:\.\d+)?)\/(-?\d+(?:\.\d+)?)/); if(!m) throw new Error('no lat/lon'); return {lat:Number(m[1]),lon:Number(m[2]),timezone:u.searchParams.get('timezone')||'',country:u.searchParams.get('country')||''}; }
  function keyOf(loc){ return `${loc.lat.toFixed(3)},${loc.lon.toFixed(3)}`; }
  function storeSet(k,v){ try{ if(typeof $persistentStore!=='undefined') $persistentStore.write(JSON.stringify(v), k); }catch(e){ log('WARN',`store write fail ${k}: ${e}`); } }
  function storeGet(k){ try{ if(typeof $persistentStore==='undefined') return null; const s=$persistentStore.read(k); return s?JSON.parse(s):null; }catch(_){ return null; } }
  function isFresh(x,ttl){ return x && x.savedAt && (Date.now()-x.savedAt)<ttl*1000; }
  function num(x){ const n=Number(x); return Number.isFinite(n)?n:null; }
  function categoryCN(aqi){ aqi=num(aqi); if(aqi==null)return ''; if(aqi<=50)return '优'; if(aqi<=100)return '良'; if(aqi<=150)return '轻度污染'; if(aqi<=200)return '中度污染'; if(aqi<=300)return '重度污染'; return '严重污染'; }
  function cleanPollutants(p){ const out={}; [['pm25',['pm25','pm2p5','pm2_5']],['pm10',['pm10']],['o3',['o3']],['no2',['no2']],['so2',['so2']],['co',['co']]].forEach(([std,keys])=>{ for(const k of keys){ if(p&&p[k]!=null){ const v=(typeof p[k]==='object'&&p[k].v!=null)?p[k].v:p[k]; const n=num(v); if(n!=null){out[std]=n; break;} } } }); return out; }
  function normalizeMinutes(list, provider){ return (list||[]).slice(0,120).map((x,i)=>({index:i,time:x.fxTime||x.datetime||x.time||x.date||null,precipMmH:num(x.precip??x.precipitation??x.value??x.intensity??x.rain)??0,probability:num(x.prob??x.probability??x.precipitationProbability),type:String(x.type||x.precipType||x.weather||provider||'')})); }
  function getJSON(url, headers, timeout){ return new Promise((resolve,reject)=>{ const timer=setTimeout(()=>reject(new Error('timeout')), timeout||7000); $httpClient.get({url,headers:headers||{}},(err,resp,data)=>{ clearTimeout(timer); if(err)return reject(err); const status=resp&&resp.status; if(status&&(status<200||status>=300))return reject(new Error(`HTTP ${status}`)); try{resolve(typeof data==='string'?JSON.parse(data):data);}catch(e){reject(new Error(`JSON parse ${e.message}`));} }); }); }
  async function fetchQWeatherMinutely(loc){ const token=ARG.QWeatherToken; if(!token) throw new Error('missing QWeather token'); const host=(ARG.QWeatherHost||'devapi.qweather.com').replace(/^https?:\/\//,'').replace(/\/+$/,''); const j=await getJSON(`https://${host}/v7/minutely/5m?location=${loc.lon},${loc.lat}&key=${encodeURIComponent(token)}`,{'Accept':'application/json'},7000); if(j.code&&!/^2/.test(String(j.code))) throw new Error(`QWeather minutely code=${j.code}`); return {provider:'QWeather',summary:j.summary||'',minutes:normalizeMinutes(j.minutely||[],'QWeather'),updatedAt:j.updateTime||new Date().toISOString()}; }
  async function fetchQWeatherAQI(loc){ const token=ARG.QWeatherToken; if(!token) throw new Error('missing QWeather token'); const host=(ARG.QWeatherHost||'devapi.qweather.com').replace(/^https?:\/\//,'').replace(/\/+$/,''); const j=await getJSON(`https://${host}/v7/air/now?location=${loc.lon},${loc.lat}&key=${encodeURIComponent(token)}`,{'Accept':'application/json'},7000); if(j.code&&!/^2/.test(String(j.code))) throw new Error(`QWeather air code=${j.code}`); const n=j.now||{}; const aqi=num(n.aqi); return {provider:'QWeather',aqi,scale:'CN',category:n.category||categoryCN(aqi),primary:n.primary||'',pollutants:cleanPollutants(n),updatedAt:n.pubTime||j.updateTime||new Date().toISOString()}; }
  async function fetchWAQI(loc){ const token=ARG.WAQIToken; if(!token) throw new Error('missing WAQI token'); const j=await getJSON(`https://api.waqi.info/feed/geo:${loc.lat};${loc.lon}/?token=${encodeURIComponent(token)}`,{'Accept':'application/json'},7000); if(j.status!=='ok') throw new Error(`WAQI status=${j.status||'unknown'}`); const d=j.data||{}; const aqi=num(d.aqi); return {provider:'WAQI',aqi,scale:'WAQI',category:categoryCN(aqi),primary:d.dominentpol||'',pollutants:cleanPollutants(d.iaqi||{}),city:d.city&&d.city.name||'',updatedAt:d.time&&(d.time.iso||d.time.s)||new Date().toISOString()}; }
  async function fetchCaiyun(loc,kinds){ const token=ARG.ColorfulCloudsToken; if(!token) throw new Error('missing ColorfulClouds token'); const j=await getJSON(`https://api.caiyunapp.com/v2.6/${encodeURIComponent(token)}/${loc.lon},${loc.lat}/weather?lang=zh_CN&unit=metric:v2&alert=false&dailysteps=10&hourlysteps=72`,{'Accept':'application/json'},7000); const r=j&&j.result||{}; const out={provider:'ColorfulClouds'}; if(kinds.nextHour){ const arr=(r.minutely&&(r.minutely.precipitation_2h||r.minutely.precipitation))||[]; out.nextHour={provider:'ColorfulClouds',summary:r.minutely&&r.minutely.description||'',minutes:normalizeMinutes(arr.map((v,i)=>({value:v,index:i})),'ColorfulClouds')}; } if(kinds.airQuality){ const aq=r.realtime&&r.realtime.air_quality||{}; const aqiObj=aq.aqi||{}; const aqi=num(aqiObj.chn??aqiObj.usa??aqiObj.value??aq.aqi); out.airQuality={provider:'ColorfulClouds',aqi,scale:aqiObj.chn!=null?'CN':(aqiObj.usa!=null?'US':''),category:categoryCN(aqi),primary:'',pollutants:cleanPollutants(aq),updatedAt:new Date().toISOString()}; } return out; }
  function choose(kind){ const v=String(ARG[kind==='nextHour'?'NextHourProvider':'AirQualityProvider']||'Auto'); if(v!=='Auto') return v; if(kind==='nextHour'){ if(ARG.QWeatherToken)return 'QWeather'; if(ARG.ColorfulCloudsToken)return 'ColorfulClouds'; return 'WeatherKit'; } if(ARG.WAQIToken)return 'WAQI'; if(ARG.QWeatherToken)return 'QWeather'; if(ARG.ColorfulCloudsToken)return 'ColorfulClouds'; return 'WeatherKit'; }
  async function prefetch(loc){ const ttl=Math.max(30,Number(ARG.ProviderCacheTTL||1800)); const key=`WeatherKit.iOS27.ProviderCache.${keyOf(loc)}`; const cached=storeGet(key); if(isFresh(cached,ttl)){ log('DEBUG',`prefetch cache fresh ${keyOf(loc)}`); return; } const np=choose('nextHour'), ap=choose('airQuality'); const bundle={savedAt:Date.now(),location:loc,selected:{nextHour:np,airQuality:ap},nextHour:null,airQuality:null,errors:[]}; const jobs=[]; if(np==='QWeather') jobs.push(fetchQWeatherMinutely(loc).then(v=>bundle.nextHour=v).catch(e=>bundle.errors.push(`QWeather nextHour:${e.message||e}`))); if(np==='ColorfulClouds') jobs.push(fetchCaiyun(loc,{nextHour:true,airQuality:false}).then(v=>bundle.nextHour=v.nextHour).catch(e=>bundle.errors.push(`ColorfulClouds nextHour:${e.message||e}`))); if(ap==='QWeather') jobs.push(fetchQWeatherAQI(loc).then(v=>bundle.airQuality=v).catch(e=>bundle.errors.push(`QWeather AQI:${e.message||e}`))); if(ap==='WAQI') jobs.push(fetchWAQI(loc).then(v=>bundle.airQuality=v).catch(e=>bundle.errors.push(`WAQI AQI:${e.message||e}`))); if(ap==='ColorfulClouds') jobs.push(fetchCaiyun(loc,{nextHour:false,airQuality:true}).then(v=>bundle.airQuality=v.airQuality).catch(e=>bundle.errors.push(`ColorfulClouds AQI:${e.message||e}`))); await Promise.all(jobs); storeSet(key,bundle); log('INFO',`prefetch ${keyOf(loc)} next=${bundle.nextHour?bundle.nextHour.provider:'none'} aq=${bundle.airQuality?bundle.airQuality.provider:'none'} errors=${bundle.errors.length}`); }
  async function main(){
    const u=new URL($request.url); let changed=false;
    if(ARG.ForceAllDataSets!=='0'){ const before=u.searchParams.get('dataSets')||''; const after=mergeDataSets(before); if(after!==before){u.searchParams.set('dataSets',after); changed=true; log('INFO',`dataSets => ${after}`);} }
    if(!u.searchParams.has('relativeDailyStart')){u.searchParams.set('relativeDailyStart','-1');changed=true;}
    if(!u.searchParams.has('relativeDailyEnd')){u.searchParams.set('relativeDailyEnd','10');changed=true;}
    if(!u.searchParams.has('periodicStart')){u.searchParams.set('periodicStart',utcLocalMidnightShift(-1));changed=true;}
    if(!u.searchParams.has('periodicEnd')){u.searchParams.set('periodicEnd',utcLocalMidnightShift(9));changed=true;}
    if(!u.searchParams.has('periodLengths')){u.searchParams.set('periodLengths','2');changed=true;}
    if(ARG.ProviderPrefetch==='1'){ try{ await prefetch(locFromUrl(u.toString())); }catch(e){ log('WARN',`prefetch fail ${e.message||e}`); } }
    if(changed) $done({url:u.toString()}); else $done({});
  }
  main().catch(e=>{ console.log(`[${NAME}] ERROR ${e&&e.stack||e}`); $done({}); });
})();
